name: "Deploy CloudFormation Stack"
on: 
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: raviaws1234/cloudformation action@v1
      env:
        AWS_STACK_NAME: 'my-simple-stack'
        AWS_REGION: 'us-east-1'
        AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
        AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
        AWS_DEPLOY_BUCKET: ${{secrets.AWS_DEPLOY_BUCKET}}
        AWS_BUCKET_PREFIX: stacks/sqs
        PARAMETER_OVERRIDES: AliasName=prod
